platform :osx, '10.15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
end

# require 'json'
# require 'pathname'
# require 'fileutils'
# workspace_dir = File.dirname(JSON.parse(`cargo locate-project --workspace`)['root'])
# cargo_target_dir = File.join(workspace_dir, 'target')
# lipo_dir= File.join(cargo_target_dir, 'lipo-darwin')
# veilid_flutter = File.join(lipo_dir, 'libveilid_flutter.dylib')
# FileUtils.mkdir_p(lipo_dir)
# FileUtils.touch(veilid_flutter)

post_install do |installer|
  project = installer.pods_project
  # reference = project.add_file_reference(veilid_flutter, project.main_group['Frameworks'])
  
  project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
  
    # if (target.is_a? Xcodeproj::Project::Object::PBXNativeTarget) && target.name == 'veilid'
    #   buildfile = target.resources_build_phase.add_file_reference(reference)
    #   buildfile.settings = { 'ATTRIBUTES' => ['CodeSignOnCopy'] }
    # end
  
  end

end
