"""Directory-ignore patterns for dagger `Ignore` annotations, generated from the repo's
.gitignore files.

Dagger evaluates `Ignore` annotations inside the module-runtime container, which mounts
only `.dagger` (not the repo root), so the patterns cannot be read from `.gitignore` at
load time. Instead this module is *generated*: `_collect()` reads every tracked
`.gitignore` in the tree (root + nested) and the list below is written by running this
file. main.py imports `DIRECTORY_IGNORE_PATTERNS`; the host->engine upload then skips
ignored paths (notably the multi-hundred-GB `target/`).

Regenerate after changing any `.gitignore` (run from anywhere in the repo):

    python .dagger/src/veilid/ignore_patterns.py

That rewrites the generated block below in place, so there is no list to hand-maintain.
"""

from pathlib import Path
import subprocess


def _collect() -> list[str]:
    """Collect dagger Ignore globs from every tracked .gitignore (host-side, via git)."""
    root = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True
    ).stdout.strip()
    listing = subprocess.run(
        ["git", "-C", root, "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
        capture_output=True, text=True, check=True,
    ).stdout
    files = sorted(f for f in listing.split("\0") if f.endswith(".gitignore"))

    # The dagger module's own files are committed (not in .gitignore) but must not be uploaded.
    pats: set[str] = {".dagger", "dagger.gen.go", "dagger.json"}
    for f in files:
        subdir = "" if f == ".gitignore" else f[: -len("/.gitignore")]
        for raw in (Path(root) / f).read_text(errors="ignore").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or line.startswith("!"):
                continue  # comments and negations aren't expressible as Ignore globs
            anchored = line.startswith("/")
            pat = line.strip("/")
            if not pat:
                continue
            if subdir:  # rebase a nested .gitignore pattern under its directory
                pats.add(f"{subdir}/{pat}" if anchored else f"{subdir}/**/{pat}")
            else:
                pats.add(pat if anchored else f"**/{pat}")
    return sorted(pats)


# BEGIN GENERATED
DIRECTORY_IGNORE_PATTERNS: list[str] = [
    '**/$RECYCLE.BIN',
    '**/**/*.rs.bk',
    '**/**/mutants.out*',
    '**/*.cab',
    '**/*.lnk',
    '**/*.log',
    '**/*.msi',
    '**/*.msix',
    '**/*.msm',
    '**/*.msp',
    '**/*.pdb',
    '**/*.stackdump',
    '**/.AppleDB',
    '**/.AppleDesktop',
    '**/.AppleDouble',
    '**/.DS_Store',
    '**/.DocumentRevisions-V100',
    '**/.LSOverride',
    '**/.Spotlight-V100',
    '**/.TemporaryItems',
    '**/.Trashes',
    '**/.VolumeIcon.icns',
    '**/._*',
    '**/.apdisk',
    '**/.claude',
    '**/.com.apple.timemachine.donotpresent',
    '**/.fseventsd',
    '**/.idea',
    '**/.pytest_cache',
    '**/.settings',
    '**/.tmp-earthly-out',
    '**/.vscode',
    '**/Icon',
    '**/Network Trash Folder',
    '**/Temporary Items',
    '**/Thumbs.db',
    '**/Thumbs.db:encryptable',
    '**/[Dd]esktop.ini',
    '**/ehthumbs.db',
    '**/ehthumbs_vista.db',
    '**/flamegraph.svg',
    '**/perf.data',
    '**/perf.data.old',
    '**/rustc-ice-*',
    '**/~*',
    '.dagger',
    '.dagger/**/__pycache__',
    '.dagger/.env',
    '.dagger/.venv',
    '.dagger/sdk',
    'dagger.gen.go',
    'dagger.json',
    'debug',
    'scripts/cicd-python/**/*$py.class',
    'scripts/cicd-python/**/**/__pycache__',
    'scripts/cicd-python/**/*.cover',
    'scripts/cicd-python/**/*.egg',
    'scripts/cicd-python/**/*.egg-info',
    'scripts/cicd-python/**/*.log',
    'scripts/cicd-python/**/*.manifest',
    'scripts/cicd-python/**/*.mo',
    'scripts/cicd-python/**/*.pot',
    'scripts/cicd-python/**/*.py,cover',
    'scripts/cicd-python/**/*.py[cod]',
    'scripts/cicd-python/**/*.sage.py',
    'scripts/cicd-python/**/*.so',
    'scripts/cicd-python/**/*.spec',
    'scripts/cicd-python/**/.Python',
    'scripts/cicd-python/**/.cache',
    'scripts/cicd-python/**/.coverage',
    'scripts/cicd-python/**/.coverage.*',
    'scripts/cicd-python/**/.dmypy.json',
    'scripts/cicd-python/**/.eggs',
    'scripts/cicd-python/**/.env',
    'scripts/cicd-python/**/.hypothesis',
    'scripts/cicd-python/**/.installed.cfg',
    'scripts/cicd-python/**/.ipynb_checkpoints',
    'scripts/cicd-python/**/.mypy_cache',
    'scripts/cicd-python/**/.nox',
    'scripts/cicd-python/**/.pdm-build',
    'scripts/cicd-python/**/.pdm-python',
    'scripts/cicd-python/**/.pdm.toml',
    'scripts/cicd-python/**/.pybuilder',
    'scripts/cicd-python/**/.pypirc',
    'scripts/cicd-python/**/.pyre',
    'scripts/cicd-python/**/.pytest_cache',
    'scripts/cicd-python/**/.pytype',
    'scripts/cicd-python/**/.ropeproject',
    'scripts/cicd-python/**/.ruff_cache',
    'scripts/cicd-python/**/.scrapy',
    'scripts/cicd-python/**/.spyderproject',
    'scripts/cicd-python/**/.spyproject',
    'scripts/cicd-python/**/.tox',
    'scripts/cicd-python/**/.venv',
    'scripts/cicd-python/**/.webassets-cache',
    'scripts/cicd-python/**/ENV',
    'scripts/cicd-python/**/MANIFEST',
    'scripts/cicd-python/**/__pycache__',
    'scripts/cicd-python/**/__pypackages__',
    'scripts/cicd-python/**/build',
    'scripts/cicd-python/**/celerybeat-schedule',
    'scripts/cicd-python/**/celerybeat.pid',
    'scripts/cicd-python/**/cover',
    'scripts/cicd-python/**/coverage.xml',
    'scripts/cicd-python/**/cython_debug',
    'scripts/cicd-python/**/db.sqlite3',
    'scripts/cicd-python/**/db.sqlite3-journal',
    'scripts/cicd-python/**/develop-eggs',
    'scripts/cicd-python/**/dist',
    'scripts/cicd-python/**/dmypy.json',
    'scripts/cicd-python/**/docs/_build',
    'scripts/cicd-python/**/downloads',
    'scripts/cicd-python/**/eggs',
    'scripts/cicd-python/**/env',
    'scripts/cicd-python/**/env.bak',
    'scripts/cicd-python/**/htmlcov',
    'scripts/cicd-python/**/instance',
    'scripts/cicd-python/**/ipython_config.py',
    'scripts/cicd-python/**/lib',
    'scripts/cicd-python/**/lib64',
    'scripts/cicd-python/**/local_settings.py',
    'scripts/cicd-python/**/nosetests.xml',
    'scripts/cicd-python/**/parts',
    'scripts/cicd-python/**/pip-delete-this-directory.txt',
    'scripts/cicd-python/**/pip-log.txt',
    'scripts/cicd-python/**/profile_default',
    'scripts/cicd-python/**/sdist',
    'scripts/cicd-python/**/share/python-wheels',
    'scripts/cicd-python/**/target',
    'scripts/cicd-python/**/var',
    'scripts/cicd-python/**/venv',
    'scripts/cicd-python/**/venv.bak',
    'scripts/cicd-python/**/wheels',
    'scripts/cicd-python/site',
    'target',
    'veilid-core/**/**/*.rs.bk',
    'veilid-core/**/bin',
    'veilid-core/**/pkg',
    'veilid-core/src/tests/android/veilid_core_android_tests/**/**/*.jks',
    'veilid-core/src/tests/android/veilid_core_android_tests/**/**/*.keystore',
    'veilid-core/src/tests/android/veilid_core_android_tests/**/*.iml',
    'veilid-core/src/tests/android/veilid_core_android_tests/**/.DS_Store',
    'veilid-core/src/tests/android/veilid_core_android_tests/**/.cxx',
    'veilid-core/src/tests/android/veilid_core_android_tests/**/.externalNativeBuild',
    'veilid-core/src/tests/android/veilid_core_android_tests/**/.gradle',
    'veilid-core/src/tests/android/veilid_core_android_tests/**/key.properties',
    'veilid-core/src/tests/android/veilid_core_android_tests/**/local.properties',
    'veilid-core/src/tests/android/veilid_core_android_tests/.idea/assetWizardSettings.xml',
    'veilid-core/src/tests/android/veilid_core_android_tests/.idea/caches',
    'veilid-core/src/tests/android/veilid_core_android_tests/.idea/deploymentTargetDropDown.xml',
    'veilid-core/src/tests/android/veilid_core_android_tests/.idea/libraries',
    'veilid-core/src/tests/android/veilid_core_android_tests/.idea/modules.xml',
    'veilid-core/src/tests/android/veilid_core_android_tests/.idea/navEditor.xml',
    'veilid-core/src/tests/android/veilid_core_android_tests/.idea/workspace.xml',
    'veilid-core/src/tests/android/veilid_core_android_tests/app/.cxx',
    'veilid-core/src/tests/android/veilid_core_android_tests/app/build',
    'veilid-core/src/tests/android/veilid_core_android_tests/build',
    'veilid-core/src/tests/android/veilid_core_android_tests/captures',
    'veilid-core/src/tests/android/veilid_core_android_tests/local.properties',
    'veilid-core/src/tests/ios/veilidcore-tests/**/*.dSYM',
    'veilid-core/src/tests/ios/veilidcore-tests/**/*.dSYM.zip',
    'veilid-core/src/tests/ios/veilidcore-tests/**/*.hmap',
    'veilid-core/src/tests/ios/veilidcore-tests/**/*.ipa',
    'veilid-core/src/tests/ios/veilidcore-tests/**/*.mode1v3',
    'veilid-core/src/tests/ios/veilidcore-tests/**/*.mode2v3',
    'veilid-core/src/tests/ios/veilidcore-tests/**/*.moved-aside',
    'veilid-core/src/tests/ios/veilidcore-tests/**/*.pbxuser',
    'veilid-core/src/tests/ios/veilidcore-tests/**/*.perspectivev3',
    'veilid-core/src/tests/ios/veilidcore-tests/**/*.xccheckout',
    'veilid-core/src/tests/ios/veilidcore-tests/**/*.xcscmblueprint',
    'veilid-core/src/tests/ios/veilidcore-tests/**/.accio',
    'veilid-core/src/tests/ios/veilidcore-tests/**/.build',
    'veilid-core/src/tests/ios/veilidcore-tests/**/Carthage/Build',
    'veilid-core/src/tests/ios/veilidcore-tests/**/Dependencies',
    'veilid-core/src/tests/ios/veilidcore-tests/**/DerivedData',
    'veilid-core/src/tests/ios/veilidcore-tests/**/build',
    'veilid-core/src/tests/ios/veilidcore-tests/**/fastlane/Preview.html',
    'veilid-core/src/tests/ios/veilidcore-tests/**/fastlane/report.xml',
    'veilid-core/src/tests/ios/veilidcore-tests/**/fastlane/screenshots/**/*.png',
    'veilid-core/src/tests/ios/veilidcore-tests/**/fastlane/test_output',
    'veilid-core/src/tests/ios/veilidcore-tests/**/iOSInjectionProject',
    'veilid-core/src/tests/ios/veilidcore-tests/**/playground.xcworkspace',
    'veilid-core/src/tests/ios/veilidcore-tests/**/timeline.xctimeline',
    'veilid-core/src/tests/ios/veilidcore-tests/**/xcuserdata',
    'veilid-core/tests/tmp',
    'veilid-flutter/**/**/doc/api',
    'veilid-flutter/**/*.class',
    'veilid-flutter/**/*.iml',
    'veilid-flutter/**/*.ipr',
    'veilid-flutter/**/*.iws',
    'veilid-flutter/**/*.log',
    'veilid-flutter/**/*.pyc',
    'veilid-flutter/**/*.swp',
    'veilid-flutter/**/.DS_Store',
    'veilid-flutter/**/.atom',
    'veilid-flutter/**/.buildlog',
    'veilid-flutter/**/.dart_tool',
    'veilid-flutter/**/.flutter',
    'veilid-flutter/**/.flutter-plugins',
    'veilid-flutter/**/.flutter-plugins-dependencies',
    'veilid-flutter/**/.gradle',
    'veilid-flutter/**/.history',
    'veilid-flutter/**/.idea',
    'veilid-flutter/**/.packages',
    'veilid-flutter/**/.svn',
    'veilid-flutter/**/build',
    'veilid-flutter/**/local.properties',
    'veilid-flutter/android/**/*.iml',
    'veilid-flutter/android/**/.DS_Store',
    'veilid-flutter/android/**/.cxx',
    'veilid-flutter/android/**/.gradle',
    'veilid-flutter/android/.idea/libraries',
    'veilid-flutter/android/.idea/workspace.xml',
    'veilid-flutter/android/build',
    'veilid-flutter/android/captures',
    'veilid-flutter/android/local.properties',
    'veilid-flutter/example/**/**/doc/api',
    'veilid-flutter/example/**/**/ios/Flutter/.last_build_id',
    'veilid-flutter/example/**/*.class',
    'veilid-flutter/example/**/*.iml',
    'veilid-flutter/example/**/*.ipr',
    'veilid-flutter/example/**/*.iws',
    'veilid-flutter/example/**/*.log',
    'veilid-flutter/example/**/*.pyc',
    'veilid-flutter/example/**/*.swp',
    'veilid-flutter/example/**/.DS_Store',
    'veilid-flutter/example/**/.atom',
    'veilid-flutter/example/**/.buildlog',
    'veilid-flutter/example/**/.dart_tool',
    'veilid-flutter/example/**/.flutter-plugins',
    'veilid-flutter/example/**/.flutter-plugins-dependencies',
    'veilid-flutter/example/**/.history',
    'veilid-flutter/example/**/.idea',
    'veilid-flutter/example/**/.packages',
    'veilid-flutter/example/**/.pub',
    'veilid-flutter/example/**/.pub-cache',
    'veilid-flutter/example/**/.svn',
    'veilid-flutter/example/**/app.*.map.json',
    'veilid-flutter/example/**/app.*.symbols',
    'veilid-flutter/example/android/**/**/*.jks',
    'veilid-flutter/example/android/**/**/*.keystore',
    'veilid-flutter/example/android/**/GeneratedPluginRegistrant.java',
    'veilid-flutter/example/android/**/gradle-wrapper.jar',
    'veilid-flutter/example/android/**/key.properties',
    'veilid-flutter/example/android/.gradle',
    'veilid-flutter/example/android/app/**/.cxx',
    'veilid-flutter/example/android/app/debug',
    'veilid-flutter/example/android/app/profile',
    'veilid-flutter/example/android/app/release',
    'veilid-flutter/example/android/captures',
    'veilid-flutter/example/android/gradlew',
    'veilid-flutter/example/android/gradlew.bat',
    'veilid-flutter/example/android/local.properties',
    'veilid-flutter/example/build',
    'veilid-flutter/example/ios/**/**/*sync',
    'veilid-flutter/example/ios/**/**/.generated',
    'veilid-flutter/example/ios/**/**/.symlinks',
    'veilid-flutter/example/ios/**/**/.vagrant',
    'veilid-flutter/example/ios/**/**/DerivedData',
    'veilid-flutter/example/ios/**/**/Pods',
    'veilid-flutter/example/ios/**/**/dgph',
    'veilid-flutter/example/ios/**/*.mode1v3',
    'veilid-flutter/example/ios/**/*.mode2v3',
    'veilid-flutter/example/ios/**/*.moved-aside',
    'veilid-flutter/example/ios/**/*.pbxuser',
    'veilid-flutter/example/ios/**/*.perspectivev3',
    'veilid-flutter/example/ios/**/.sconsign.dblite',
    'veilid-flutter/example/ios/**/.tags*',
    'veilid-flutter/example/ios/**/Flutter/App.framework',
    'veilid-flutter/example/ios/**/Flutter/Flutter.framework',
    'veilid-flutter/example/ios/**/Flutter/Flutter.podspec',
    'veilid-flutter/example/ios/**/Flutter/Generated.xcconfig',
    'veilid-flutter/example/ios/**/Flutter/app.flx',
    'veilid-flutter/example/ios/**/Flutter/app.zip',
    'veilid-flutter/example/ios/**/Flutter/ephemeral',
    'veilid-flutter/example/ios/**/Flutter/flutter_assets',
    'veilid-flutter/example/ios/**/Flutter/flutter_export_environment.sh',
    'veilid-flutter/example/ios/**/Icon?',
    'veilid-flutter/example/ios/**/Runner/GeneratedPluginRegistrant.*',
    'veilid-flutter/example/ios/**/ServiceDefinitions.json',
    'veilid-flutter/example/ios/**/profile',
    'veilid-flutter/example/ios/**/xcuserdata',
    'veilid-flutter/example/linux/**/flutter/ephemeral',
    'veilid-flutter/example/macos/**/**/Flutter/ephemeral',
    'veilid-flutter/example/macos/**/**/Pods',
    'veilid-flutter/example/macos/**/**/dgph',
    'veilid-flutter/example/macos/**/**/xcuserdata',
    'veilid-flutter/example/windows/**/*.[Cc]ache',
    'veilid-flutter/example/windows/**/*.sln.docstates',
    'veilid-flutter/example/windows/**/*.suo',
    'veilid-flutter/example/windows/**/*.user',
    'veilid-flutter/example/windows/**/*.userosscache',
    'veilid-flutter/example/windows/**/flutter/ephemeral',
    'veilid-flutter/example/windows/**/x64',
    'veilid-flutter/example/windows/**/x86',
    'veilid-flutter/ios/**/*.mode1v3',
    'veilid-flutter/ios/**/*.mode2v3',
    'veilid-flutter/ios/**/*.moved-aside',
    'veilid-flutter/ios/**/*.pbxuser',
    'veilid-flutter/ios/**/*.perspectivev3',
    'veilid-flutter/ios/**/*.pyc',
    'veilid-flutter/ios/**/*.swp',
    'veilid-flutter/ios/**/*sync',
    'veilid-flutter/ios/**/.DS_Store',
    'veilid-flutter/ios/**/.generated',
    'veilid-flutter/ios/**/.idea',
    'veilid-flutter/ios/**/.sconsign.dblite',
    'veilid-flutter/ios/**/.svn',
    'veilid-flutter/ios/**/.tags*',
    'veilid-flutter/ios/**/.vagrant',
    'veilid-flutter/ios/**/DerivedData',
    'veilid-flutter/ios/**/GeneratedPluginRegistrant.h',
    'veilid-flutter/ios/**/GeneratedPluginRegistrant.m',
    'veilid-flutter/ios/**/Icon?',
    'veilid-flutter/ios/**/build',
    'veilid-flutter/ios/**/profile',
    'veilid-flutter/ios/**/xcuserdata',
    'veilid-flutter/ios/Flutter/Generated.xcconfig',
    'veilid-flutter/ios/Flutter/ephemeral',
    'veilid-flutter/ios/Flutter/flutter_export_environment.sh',
    'veilid-flutter/ios/veilid-flutter/**/.build',
    'veilid-flutter/ios/veilid-flutter/**/.swiftpm/configuration/xcuserdata',
    'veilid-flutter/ios/veilid-flutter/**/.swiftpm/xcode/xcuserdata',
    'veilid-flutter/macos/veilid-flutter/**/.build',
    'veilid-flutter/macos/veilid-flutter/**/.swiftpm/configuration/xcuserdata',
    'veilid-flutter/macos/veilid-flutter/**/.swiftpm/xcode/xcuserdata',
    'veilid-flutter/packages/veilid_test/**/.dart_tool',
    'veilid-flutter/packages/veilid_test/**/.flutter-plugins',
    'veilid-flutter/packages/veilid_test/**/.flutter-plugins-dependencies',
    'veilid-flutter/packages/veilid_test/**/pubspec.lock',
    'veilid-flutter/pubspec.lock',
    'veilid-flutter/rust/**/$RECYCLE.BIN',
    'veilid-flutter/rust/**/*.cab',
    'veilid-flutter/rust/**/*.lnk',
    'veilid-flutter/rust/**/*.msi',
    'veilid-flutter/rust/**/*.msix',
    'veilid-flutter/rust/**/*.msm',
    'veilid-flutter/rust/**/*.msp',
    'veilid-flutter/rust/**/*.stackdump',
    'veilid-flutter/rust/**/.AppleDB',
    'veilid-flutter/rust/**/.AppleDesktop',
    'veilid-flutter/rust/**/.AppleDouble',
    'veilid-flutter/rust/**/.DS_Store',
    'veilid-flutter/rust/**/.DocumentRevisions-V100',
    'veilid-flutter/rust/**/.LSOverride',
    'veilid-flutter/rust/**/.Spotlight-V100',
    'veilid-flutter/rust/**/.TemporaryItems',
    'veilid-flutter/rust/**/.Trashes',
    'veilid-flutter/rust/**/.VolumeIcon.icns',
    'veilid-flutter/rust/**/._*',
    'veilid-flutter/rust/**/.apdisk',
    'veilid-flutter/rust/**/.com.apple.timemachine.donotpresent',
    'veilid-flutter/rust/**/.config',
    'veilid-flutter/rust/**/.dart',
    'veilid-flutter/rust/**/.flutter',
    'veilid-flutter/rust/**/.fseventsd',
    'veilid-flutter/rust/**/Icon',
    'veilid-flutter/rust/**/Network Trash Folder',
    'veilid-flutter/rust/**/Temporary Items',
    'veilid-flutter/rust/**/Thumbs.db',
    'veilid-flutter/rust/**/Thumbs.db:encryptable',
    'veilid-flutter/rust/**/[Dd]esktop.ini',
    'veilid-flutter/rust/**/ehthumbs.db',
    'veilid-flutter/rust/**/ehthumbs_vista.db',
    'veilid-flutter/rust/**/logs',
    'veilid-flutter/rust/**/target',
    'veilid-flutter/windows/**/*.[Cc]ache',
    'veilid-flutter/windows/**/*.sln.docstates',
    'veilid-flutter/windows/**/*.suo',
    'veilid-flutter/windows/**/*.user',
    'veilid-flutter/windows/**/*.userosscache',
    'veilid-flutter/windows/**/flutter',
    'veilid-flutter/windows/**/x64',
    'veilid-flutter/windows/**/x86',
    'veilid-python/**/*$py.class',
    'veilid-python/**/*.cover',
    'veilid-python/**/*.egg',
    'veilid-python/**/*.egg-info',
    'veilid-python/**/*.log',
    'veilid-python/**/*.manifest',
    'veilid-python/**/*.mo',
    'veilid-python/**/*.pot',
    'veilid-python/**/*.py,cover',
    'veilid-python/**/*.py[cod]',
    'veilid-python/**/*.sage.py',
    'veilid-python/**/*.so',
    'veilid-python/**/*.spec',
    'veilid-python/**/.Python',
    'veilid-python/**/.cache',
    'veilid-python/**/.coverage',
    'veilid-python/**/.coverage.*',
    'veilid-python/**/.dmypy.json',
    'veilid-python/**/.eggs',
    'veilid-python/**/.env',
    'veilid-python/**/.hypothesis',
    'veilid-python/**/.installed.cfg',
    'veilid-python/**/.ipynb_checkpoints',
    'veilid-python/**/.mypy_cache',
    'veilid-python/**/.nox',
    'veilid-python/**/.pdm.toml',
    'veilid-python/**/.pybuilder',
    'veilid-python/**/.pyre',
    'veilid-python/**/.pytest_cache',
    'veilid-python/**/.python-version',
    'veilid-python/**/.pytype',
    'veilid-python/**/.ropeproject',
    'veilid-python/**/.scrapy',
    'veilid-python/**/.spyderproject',
    'veilid-python/**/.spyproject',
    'veilid-python/**/.tox',
    'veilid-python/**/.venv',
    'veilid-python/**/.webassets-cache',
    'veilid-python/**/ENV',
    'veilid-python/**/MANIFEST',
    'veilid-python/**/__pycache__',
    'veilid-python/**/__pypackages__',
    'veilid-python/**/build',
    'veilid-python/**/celerybeat-schedule',
    'veilid-python/**/celerybeat.pid',
    'veilid-python/**/cover',
    'veilid-python/**/coverage.xml',
    'veilid-python/**/cython_debug',
    'veilid-python/**/db.sqlite3',
    'veilid-python/**/db.sqlite3-journal',
    'veilid-python/**/develop-eggs',
    'veilid-python/**/dist',
    'veilid-python/**/dmypy.json',
    'veilid-python/**/docs/_build',
    'veilid-python/**/downloads',
    'veilid-python/**/eggs',
    'veilid-python/**/env',
    'veilid-python/**/env.bak',
    'veilid-python/**/htmlcov',
    'veilid-python/**/instance',
    'veilid-python/**/ipython_config.py',
    'veilid-python/**/lib',
    'veilid-python/**/lib64',
    'veilid-python/**/local_settings.py',
    'veilid-python/**/nosetests.xml',
    'veilid-python/**/parts',
    'veilid-python/**/pip-delete-this-directory.txt',
    'veilid-python/**/pip-log.txt',
    'veilid-python/**/profile_default',
    'veilid-python/**/sdist',
    'veilid-python/**/share/python-wheels',
    'veilid-python/**/target',
    'veilid-python/**/var',
    'veilid-python/**/venv',
    'veilid-python/**/venv.bak',
    'veilid-python/**/wheels',
    'veilid-python/site',
    'veilid-server/**/*flame*',
    'veilid-server/**/*profile*',
    'veilid-tools/src/tests/**/tmp/*',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/**/*.iml',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/**/.DS_Store',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/**/.cxx',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/**/.externalNativeBuild',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/**/.gradle',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/**/local.properties',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/.idea/assetWizardSettings.xml',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/.idea/caches',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/.idea/deploymentTargetDropDown.xml',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/.idea/libraries',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/.idea/modules.xml',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/.idea/navEditor.xml',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/.idea/workspace.xml',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/app/.cxx',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/app/build',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/build',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/captures',
    'veilid-tools/src/tests/android/veilid_tools_android_tests/local.properties',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/*.dSYM',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/*.dSYM.zip',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/*.hmap',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/*.ipa',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/*.mode1v3',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/*.mode2v3',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/*.moved-aside',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/*.pbxuser',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/*.perspectivev3',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/*.xccheckout',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/*.xcscmblueprint',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/.accio',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/.build',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/Carthage/Build',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/Dependencies',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/DerivedData',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/build',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/fastlane/Preview.html',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/fastlane/report.xml',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/fastlane/screenshots/**/*.png',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/fastlane/test_output',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/iOSInjectionProject',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/playground.xcworkspace',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/timeline.xctimeline',
    'veilid-tools/src/tests/ios/veilidtools-tests/**/xcuserdata',
    'veilid-wasm/**/**/*.rs.bk',
    'veilid-wasm/**/bin',
    'veilid-wasm/**/pkg',
    'veilid-wasm/example/test-bench/**/*.local',
    'veilid-wasm/example/test-bench/**/*.log',
    'veilid-wasm/example/test-bench/**/*.njsproj',
    'veilid-wasm/example/test-bench/**/*.ntvs*',
    'veilid-wasm/example/test-bench/**/*.sln',
    'veilid-wasm/example/test-bench/**/*.suo',
    'veilid-wasm/example/test-bench/**/*.sw?',
    'veilid-wasm/example/test-bench/**/.DS_Store',
    'veilid-wasm/example/test-bench/**/.idea',
    'veilid-wasm/example/test-bench/**/.vscode/*',
    'veilid-wasm/example/test-bench/**/dist',
    'veilid-wasm/example/test-bench/**/dist-ssr',
    'veilid-wasm/example/test-bench/**/lerna-debug.log*',
    'veilid-wasm/example/test-bench/**/logs',
    'veilid-wasm/example/test-bench/**/node_modules',
    'veilid-wasm/example/test-bench/**/npm-debug.log*',
    'veilid-wasm/example/test-bench/**/pnpm-debug.log*',
    'veilid-wasm/example/test-bench/**/yarn-debug.log*',
    'veilid-wasm/example/test-bench/**/yarn-error.log*',
    'veilid-wasm/target',
    'veilid-wasm/tests/**/coverage',
    'veilid-wasm/tests/**/node_modules',
    'veilid-wasm/tests/**/test_results',
]
# END GENERATED


if __name__ == "__main__":
    import re

    patterns = _collect()
    block = "DIRECTORY_IGNORE_PATTERNS: list[str] = [\n" + "".join(
        f"    {p!r},\n" for p in patterns
    ) + "]\n"
    path = Path(__file__)
    new = re.sub(
        r"# BEGIN GENERATED\n.*?# END GENERATED",
        f"# BEGIN GENERATED\n{block}# END GENERATED",
        path.read_text(),
        flags=re.S,
    )
    path.write_text(new)
    print(f"regenerated {len(patterns)} ignore patterns into {path.name}")
