from enum import StrEnum
from typing import Self


class Operation(StrEnum):
    CONTROL = "Control"
    GET_STATE = "GetState"
    IS_SHUTDOWN = "IsShutdown"
    ATTACH = "Attach"
    DETACH = "Detach"
    GENERATE_MEMBER_ID = "GenerateMemberId"
    GET_DHT_RECORD_KEY = "GetDhtRecordKey"
    TRANSACT_DHT_RECORDS = "TransactDhtRecords"
    NEW_PRIVATE_ROUTE = "NewPrivateRoute"
    NEW_CUSTOM_PRIVATE_ROUTE = "NewCustomPrivateRoute"
    IMPORT_REMOTE_PRIVATE_ROUTE = "ImportRemotePrivateRoute"
    RELEASE_PRIVATE_ROUTE = "ReleasePrivateRoute"
    APP_CALL_REPLY = "AppCallReply"
    NEW_ROUTING_CONTEXT = "NewRoutingContext"
    ROUTING_CONTEXT = "RoutingContext"
    OPEN_TABLE_DB = "OpenTableDb"
    DELETE_TABLE_DB = "DeleteTableDb"
    TABLE_DB = "TableDb"
    TABLE_DB_TRANSACTION = "TableDbTransaction"
    DHT_TRANSACTION = "DhtTransaction"
    GET_CRYPTO_SYSTEM = "GetCryptoSystem"
    CRYPTO_SYSTEM = "CryptoSystem"
    VERIFY_SIGNATURES = "VerifySignatures"
    GENERATE_SIGNATURES = "GenerateSignatures"
    GENERATE_KEY_PAIR = "GenerateKeyPair"
    NOW = "Now"
    NOW_NON_DECREASING = "NowNonDecreasing"
    NOW_INCREASING = "NowIncreasing"
    DEBUG = "Debug"
    VEILID_VERSION_STRING = "VeilidVersionString"
    VEILID_VERSION = "VeilidVersion"
    VEILID_FEATURES = "VeilidFeatures"
    DEFAULT_VEILID_CONFIG = "DefaultVeilidConfig"
    VALID_CRYPTO_KINDS = "ValidCryptoKinds"


class RoutingContextOperation(StrEnum):
    INVALID_ID = "InvalidId"
    RELEASE = "Release"
    WITH_DEFAULT_SAFETY = "WithDefaultSafety"
    WITH_SAFETY = "WithSafety"
    WITH_SEQUENCING = "WithSequencing"
    SAFETY = "Safety"
    APP_CALL = "AppCall"
    APP_MESSAGE = "AppMessage"
    CREATE_DHT_RECORD = "CreateDhtRecord"
    OPEN_DHT_RECORD = "OpenDhtRecord"
    CLOSE_DHT_RECORD = "CloseDhtRecord"
    DELETE_DHT_RECORD = "DeleteDhtRecord"
    GET_DHT_VALUE = "GetDhtValue"
    SET_DHT_VALUE = "SetDhtValue"
    WATCH_DHT_VALUES = "WatchDhtValues"
    CANCEL_DHT_WATCH = "CancelDhtWatch"
    INSPECT_DHT_RECORD = "InspectDhtRecord"
    FLUSH_DHT_RECORD = "FlushDhtRecord"


class TableDbOperation(StrEnum):
    INVALID_ID = "InvalidId"
    RELEASE = "Release"
    GET_COLUMN_COUNT = "GetColumnCount"
    GET_KEYS = "GetKeys"
    TRANSACT = "Transact"
    STORE = "Store"
    LOAD = "Load"
    DELETE = "Delete"


class TableDbTransactionOperation(StrEnum):
    INVALID_ID = "InvalidId"
    COMMIT = "Commit"
    ROLLBACK = "Rollback"
    STORE = "Store"
    DELETE = "Delete"


class DhtTransactionOperation(StrEnum):
    INVALID_ID = "InvalidId"
    COMMIT = "Commit"
    ROLLBACK = "Rollback"
    EXTEND = "Extend"
    GET = "Get"
    SET = "Set"
    INSPECT = "Inspect"


class CryptoSystemOperation(StrEnum):
    INVALID_ID = "InvalidId"
    RELEASE = "Release"
    KIND = "Kind"
    CACHED_DH = "CachedDh"
    COMPUTE_DH = "ComputeDh"
    GENERATE_SHARED_SECRET = "GenerateSharedSecret"
    HPKE_SEAL = "HpkeSeal"
    HPKE_OPEN = "HpkeOpen"
    GENERATE_KEM_KEY_PAIR = "GenerateKemKeyPair"
    ENCAPSULATION_KEY_FROM_SIGNING_KEY = "EncapsulationKeyFromSigningKey"
    DECAPSULATION_KEY_FROM_SIGNING_SECRET = "DecapsulationKeyFromSigningSecret"
    ENCAPSULATION_KEY_LENGTH = "EncapsulationKeyLength"
    DECAPSULATION_KEY_LENGTH = "DecapsulationKeyLength"
    RANDOM_BYTES = "RandomBytes"
    SHARED_SECRET_LENGTH = "SharedSecretLength"
    NONCE_LENGTH = "NonceLength"
    HASH_DIGEST_LENGTH = "HashDigestLength"
    PUBLIC_KEY_LENGTH = "PublicKeyLength"
    SECRET_KEY_LENGTH = "SecretKeyLength"
    SIGNATURE_LENGTH = "SignatureLength"
    DEFAULT_SALT_LENGTH = "DefaultSaltLength"
    AEAD_OVERHEAD = "AeadOverhead"
    CHECK_SHARED_SECRET = "CheckSharedSecret"
    CHECK_NONCE = "CheckNonce"
    CHECK_HASH_DIGEST = "CheckHashDigest"
    CHECK_PUBLIC_KEY = "CheckPublicKey"
    CHECK_SECRET_KEY = "CheckSecretKey"
    CHECK_SIGNATURE = "CheckSignature"
    HASH_PASSWORD = "HashPassword"
    VERIFY_PASSWORD = "VerifyPassword"
    DERIVE_SHARED_SECRET = "DeriveSharedSecret"
    RANDOM_NONCE = "RandomNonce"
    RANDOM_SHARED_SECRET = "RandomSharedSecret"
    GENERATE_KEY_PAIR = "GenerateKeyPair"
    GENERATE_HASH = "GenerateHash"
    VALIDATE_KEY_PAIR = "ValidateKeyPair"
    VALIDATE_HASH = "ValidateHash"
    DISTANCE = "Distance"
    SIGN = "Sign"
    VERIFY = "Verify"
    DECRYPT_AEAD = "DecryptAead"
    ENCRYPT_AEAD = "EncryptAead"
    CRYPT_NO_AUTH = "CryptNoAuth"


class RecvMessageType(StrEnum):
    RESPONSE = "Response"
    UPDATE = "Update"
